### ISSUE TITLE
**/designprimerresults/*.fa': No such file or directory

### ISSUE THREAD

**Issue by suviu001** [MoradMMokhtar/MegaSSR#1]
Hello! When I run this software package, the following error occurs. Run example is ok. The previous steps was not completed, and the next step started, resulting in this error?
```
cat: '/home/suviu/software/MegaSSR/Results/Esag_SSR_result/designprimerresults/*.fa': No such file or directory
cat: '/home/suviu/software/MegaSSR/Results/Esag_SSR_result/gdesignprimerresults/*.fa': No such file or directory
awk: fatal: cannot open file `/home/suviu/software/MegaSSR/Results/Esag_SSR_result/intermediate_Files_step_1/Esag_SSR_result.Extract-Genic-seq-out.fasta.results2.txt' for reading: No such file or directory
```

**Comment by MoradMMokhtar** [comment]
@suviu001 Thank you for using MegaSSR. The error occurs because MegaSSR cannot find the fasta file in the Design SSR Primer step. When you run MegaSSR, the tool writes the steps to the terminal. Can you share them with me to find out where the problem is?

**Comment by suviu001** [comment]
> @suviu001 Thank you for using MegaSSR. The error occurs because MegaSSR cannot find the fasta file in the Design SSR Primer step. When you run MegaSSR, the tool writes the steps to the terminal. Can you share them with me to find out where the problem is?

Ok，but my input  file (genome) is about 3.6 G, How can i send the file to you? As shown above, Error message：
`(MegaSSR) suviu@suviu:~/software/MegaSSR$ bash MegaSSR.sh -A 1 -F Data_For_Test/Esag.genome.fa -P test123

        #############################################
        ##############  MegaSSR v2.1.0  ##############
        #############################################

        Contributors: Morad M Mokhtar,  Alsamman M. Alsamman, Achraf El Allali

        Wed Apr  5 17:04:41 CST 2023     Start time

        Parameters: -A 1 -F Data_For_Test/Esag.genome.fa -G  -P test123 -1 10 -2 6 -3 5 -4 4 -5 3 -6 3 -C 100 -s 18 -O 20 -S 22 -R 250-500 -t 4 -B no -L 1000 -I 50

        Check the FASTA File format.
MegaSSR.sh: line 199:   904 Killed                  faidx --split-files $outdir/"$sequence_acc"_genomic.fa


        Wed Apr  5 17:05:22 CST 2023    Simple Sequence Repeat identification started



        Wed Apr  5 17:05:22 CST 2023    Identifying SSR Done



        Wed Apr  5 17:05:22 CST 2023    Preparing statistics files



        Wed Apr  5 17:05:22 CST 2023    Design SSR primers started

cat: '/home/suviu/software/MegaSSR/Results/test123/designprimerresults/*.fa': No such file or directory


        Wed Apr  5 17:05:22 CST 2023    Design SSR primers Done



        Wed Apr  5 17:05:27 CST 2023    Drawing plots Done

MegaSSR.sh: line 336: /ssr.sorted.gff3: Permission denied
MegaSSR.sh: line 337: bgzip: command not found
MegaSSR.sh: line 338: tabix: command not found
MegaSSR.sh: line 341: /primers.sorted.gff3: Permission denied
MegaSSR.sh: line 342: bgzip: command not found
MegaSSR.sh: line 343: tabix: command not found
cp: cannot stat '/home/suviu/software/MegaSSR/bin/Script/tracks/tracks.conf': No such file or directory
cp: cannot create regular file '/fasta.fasta': Permission denied
MegaSSR.sh: line 346: samtools: command not found
cp: missing file operand
Try 'cp --help' for more information.
        Wed Apr  5 17:05:27 CST 2023    MegaSSR Done, The results saved in (/home/suviu/software/MegaSSR/Results/test123)
mv: replace '/home/suviu/software/MegaSSR/Results/test123/Desinged SSR primer.csv', overriding mode 0644 (rw-r--r--)? ^C
(MegaSSR) suviu@suviu:~/software/MegaSSR$`

**Comment by MoradMMokhtar** [comment]
@suviu001 
it seems that the genome sequence is huge and the CPU or RAM memory of your computer is not able to process the first step to split the huge file into many small FASTA files, so what is the specification of your computer?
If you have the ability to split this huge file into chromosomes or small files, you can run each file individually.
Another solution I prefer when using MegaSSR with such a large genome on a small computer is to use the MegaSSR web server (https://bioinformatics.um6p.ma/MegaSSR/). Also, I recommend you to set the Mononucleotides option to zero if you do not need it, because the analysis with the Mononucleotides option takes long time.
