### ISSUE TITLE
MegaSSR website could not be accessed

### ISSUE THREAD

**Issue by faizalrezha** [MoradMMokhtar/MegaSSR#2]
Hi! I hope you are doing well.

I encountered a problem while accessing the MegaSSR website. 
![Capture](https://github.com/MoradMMokhtar/MegaSSR/assets/171125602/874a7fef-8f3a-4f80-ab24-c38e7e16e2ed)

Would you mind is there anything I could do about this issue?

Thank you for your help. I look forward to hearing from you.

**Comment by MoradMMokhtar** [comment]
Dear @faizalrezha 
I tested the MegaSSR website (https://bioinformatics.um6p.ma/MegaSSR/) and it is working fine, so we do not have any issues on our side, maybe you need to check your administrator.  The possible reasons could include firewall, internet, and browser issues.
Maybe you can change the browser or the network and check it again
Please keep me know with the update

**Comment by faizalrezha** [comment]
Dear @MoradMMokhtar 

Yes, as you said, there is no problem at all for now. Thank you for your response.

Best regards,
Rezha
